const LAST_UPDATED = "June 1, 2026";

export default function TermsPage() {
  return (
    <main className="px-5 py-8 max-w-2xl mx-auto space-y-4">
      <header>
        <h1 className="font-display text-3xl text-ink-900 mb-2">Terms and Conditions</h1>
        <p className="text-sm text-ink-500">Last updated: {LAST_UPDATED}</p>
        <p className="text-xs text-amber-700 font-semibold bg-amber-50 border border-amber-200 rounded-xl px-4 py-2 mt-3">
          Notice: These terms and policies should be reviewed by a qualified attorney before deployment.
        </p>
      </header>

      <Section title="What this app is">
        <p>
          This application is a private care coordination and manual recordkeeping tool designed for personal, family, and household care management. It is designed solely to help organize schedules, notes, safety items, tasks, communications, and historical references for family members and caregiver coordinates.
        </p>
      </Section>

      <Section title="Not Medical or Emergency Services">
        <p>
          This app does not provide medical advice, diagnosis, treatment, or clinical emergency dispatch services. It is not a substitute for professional medical judgment, licensed nursing care, physician orders, or emergency response systems.
        </p>
        <p className="font-semibold text-ink-950 mt-2">
          IN AN EMERGENCY, CALL LOCAL EMERGENCY SERVICES (SUCH AS 911) IMMEDIATELY.
        </p>
      </Section>

      <Section title="No Professional Advice">
        <p>
          The records and summaries generated by this app are for personal reference and recordkeeping only. They do not constitute legal advice, tax advice, payroll advice, insurance advice, accounting advice, or formal employment determination. Users must seek professional advice from qualified experts for all tax, payroll, legal, and financial decisions.
        </p>
      </Section>

      <Section title="Independent Contractor Status & Taxes">
        <p>
          All caregivers coordinating care through this application are considered independent contractors and are not employees of the household or client. Caregivers are solely responsible for determining their own tax obligations, completing their own records, and paying any self-employment or other taxes.
        </p>
        <p className="mt-2 font-medium">
          No W-2, 1099, or other tax forms will be prepared, generated, or issued by the client, homeowner, or through this application.
        </p>
        <p className="mt-2">
          Invoice logs and year-end summaries generated in this app are strictly manual recordkeeping tools to assist caregivers in tracking shift histories for their personal tax preparation and record keeping.
        </p>
      </Section>

      <Section title="No Payroll or Deductions Support">
        <p>
          No tax deductions, payroll withholdings, social security contributions, or employer tax processing features exist in this private application. All caregiver compensation calculations are unverified estimates for manual recordkeeping only.
        </p>
      </Section>

      <Section title="Information Accuracy, Geofencing, & Bulk Actions">
        <p>
          Users are entirely responsible for entering complete and accurate schedules, contact records, allergy alerts, medication lists, safety details, and care guides. The client and caregivers must keep information updated to ensure safety.
        </p>
        <p className="mt-2">
          Location-based geofence checks are strictly for check-in and check-out verification. The application does not perform continuous, real-time location tracking or active geofence monitoring.
        </p>
        <p className="mt-2 font-semibold text-ink-950">
          Bulk Shift Actions: Deleting or cancelling shifts bulk will permanently delete associated tasks, check-in history, and records, which can affect invoices, caregiver pay histories, and reports. Users are strictly responsible for reviewing and confirming all selections before executing bulk actions.
        </p>
      </Section>

      <Section title="Notification and Alerts Limitations">
        <p>
          Alerts, messages, notifications, and reminders generated by the application may fail, be delayed, be blocked, or be disabled due to browser configurations, device settings, networks, or power outages. Do not rely on notifications for critical tasks or time-sensitive health emergencies.
        </p>
      </Section>

      <Section title="HIPAA and Health Data Notice">
        <p>
          This private application is a personal coordination tool and is not HIPAA-compliant. The application does not operate under a Health Insurance Portability and Accountability Act (HIPAA) compliance program, and no Business Associate Agreement (BAA) is in place.
        </p>
      </Section>

      <Section title="Homeowner Liability Limits">
        <p>
          The homeowner, family members, and care recipients are not responsible for any personal injury, property damage, accidents, or liabilities incurred by caregivers beyond what standard homeowner insurance policies allow or applicable local law strictly requires. Caregivers utilize the private residence and the application at their own risk.
        </p>
      </Section>

      <Section title="Platform Identity">
        <p>
          This application is powered by the Carer Vista Pro software platform. Using organizations, families, and coordinates do not own or claim ownership of the software platform.
        </p>
      </Section>
    </main>
  );
}

function Section({
  title,
  children,
}: {
  title: string;
  children: React.ReactNode;
}) {
  return (
    <section className="bg-white rounded-3xl shadow-soft p-5 grain-overlay">
      <h2 className="font-display text-lg text-ink-900 mb-2">{title}</h2>
      <div className="text-sm text-ink-700 space-y-2">{children}</div>
    </section>
  );
}
